export const SNAP_STATUS = {
  ALREADY_ON_RUBIC: 'ALREADY_ON_RUBIC',
  UNABLE_TO_CALCULATE_ROUTE: 'UNABLE_TO_CALCULATE_ROUTE',
  NETWORK_NOT_SUPPORTED: 'NETWORK_NOT_SUPPORTED',
  TRADE_CALCULATED: 'TRADE_CALCULATED',
} as const;

export type SnapStatus = (typeof SNAP_STATUS)[keyof typeof SNAP_STATUS];
